const icons={arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',left:'<path d="m14 5-7 7 7 7"/>',right:'<path d="m10 5 7 7-7 7"/>',book:'<path d="M12 5v15M3 4c4-1 6 0 9 1 3-1 5-2 9-1v15c-4-1-6 0-9 1-3-1-5-2-9-1z"/>',paper:'<path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6m-6 4h6"/>',palette:'<path d="M12 3a9 9 0 1 0 0 18h1a2 2 0 0 0 1-4c-1-1 0-3 2-3h2c5 0 4-11-6-11Z"/><circle cx="7" cy="10" r=".7"/><circle cx="11" cy="7" r=".7"/><circle cx="16" cy="8" r=".7"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/>',photo:'<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8" cy="8" r="1.5"/><path d="m3 18 6-6 4 4 3-3 5 5"/>',check:'<path d="m5 12 4 4L19 6"/>',zoom:'<path d="M9 3H3v6m12-6h6v6M3 15v6h6m12-6v6h-6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;
const templates=[
{id:'birthday',name:'С днём рождения',tag:'Для самого особенного дня',subtitle:'Целый журнал о человеке, которого вы любите.',description:'Любимые фотографии, тёплые поздравления и маленькие истории, которые делают этот год особенным. Подарок, в котором каждое слово — о нём.',accent:'#a46b59',spreadTitle:'Твой особенный год',spreadLabel:'Праздничный разворот',spreadDescription:'Портрет именинницы, фотографии праздника и слова от близких.',chapters:['История именинника','Поздравления близких','Лучшие моменты года'],hint:'Для дня рождения друга, сестры или любимого человека.'},
{id:'mama',name:'Для мамы',tag:'Самому близкому человеку',subtitle:'Все ваши «спасибо» — под одной обложкой.',description:'Семейные снимки, воспоминания из детства и слова, которые не всегда получается сказать вслух. Соберите для мамы журнал о любви, которая всегда рядом.',accent:'#6e7555',spreadTitle:'Спасибо, мама',spreadLabel:'Семейный разворот',spreadDescription:'Тёплое письмо маме, семейные фотографии и дорогие сердцу детали.',chapters:['Письмо маме','Наш семейный альбом','За что я благодарю тебя'],hint:'Для маминого дня рождения, праздника или просто так.'},
{id:'love',name:'История любви',tag:'Всё о вас двоих',subtitle:'От первой встречи до вашего «навсегда».',description:'Первое свидание, любимые места и ваши маленькие традиции. Сохраните историю, которую знаете только вы, в журнале с кинематографичными фотографиями и личными словами.',accent:'#746358',spreadTitle:'С нашей первой встречи',spreadLabel:'История вашей пары',spreadDescription:'Воспоминания о знакомстве, совместные снимки и важные даты.',chapters:['Как мы встретились','Наши места и традиции','Письмо любимому человеку'],hint:'К годовщине, свадьбе или ещё одному счастливому дню вместе.'},
{id:'blank',name:'Свой макет',tag:'Для истории без правил',subtitle:'Ваша идея. Ваш ритм. Ваш журнал.',description:'Путешествие к морю, год в фотографиях или история дружбы. Начните с лаконичной композиции и наполните страницы тем, что хочется оставить с собой.',accent:'#927260',spreadTitle:'Места, где мы счастливы',spreadLabel:'Дневник путешествия',spreadDescription:'Путевые заметки, любимые города и фотографии с морского побережья.',chapters:['Места и впечатления','Личные заметки','Фотографии в деталях'],hint:'Показан пример путешествия. Тему и наполнение выбираете вы.'}
];
const app=document.querySelector('#app');
const imageAsset=(kind,id,alt,classes='',sizes='100vw',eager=false)=>{const widths=kind==='cover'?[160,480,960]:[160,768,1536],base='./assets/'+kind+'-'+id+'-spiral';const set=format=>widths.map(w=>base+'-'+w+'.'+format+' '+w+'w').join(',');return '<picture class="responsive-picture"><source type="image/avif" srcset="'+set('avif')+'" sizes="'+sizes+'"><img class="'+classes+'" src="'+base+'-'+widths[1]+'.webp" srcset="'+set('webp')+'" sizes="'+sizes+'" alt="'+alt+'" width="'+(kind==='cover'?1024:1536)+'" height="'+(kind==='cover'?1536:1024)+'" '+(eager?'loading="eager" fetchpriority="'+(classes.includes('hero-back')?'auto':'high')+'"':'loading="lazy"')+' decoding="async"></picture>';};
const cover=(t,extra='',eager=false,sizes)=>imageAsset('cover',t.id,'Обложка журнала «'+t.name+'» на пружинке','cover '+extra,sizes||(extra.startsWith('hero-')?'(max-width:700px) 42vw, 360px':'(max-width:700px) 44vw, 260px'),eager);
const categoryNav=(services=false)=>'<nav class="category-switch" aria-label="Категории товаров"><a href="#/#templates" '+(!services?'aria-current="page"':'')+'>Журналы</a><a href="#/services" '+(services?'aria-current="page"':'')+'>Прочие услуги</a></nav>';
const serviceGroups=[
{id:'gifts',label:'Подарки с фотографиями',intro:'Для любимых снимков, которые хочется держать рядом.',poster:'gifts',posterExtra:'gifts-more',items:[
['Полароидный дисплей','1 000 ₽','8 ламинированных фотографий в стиле Polaroid. С помощью механизма фотографии перелистываются одна за другой. В стоимость входят подарочная упаковка, тишью и открытка.'],
['Фотокнижка','700 ₽','6 фотографий. Современный стиль и раскрывающаяся конструкция. В стоимость входят подарочная упаковка, тишью и открытка.'],
['Рамка акриловая 10 × 15 см','250 ₽','С магнитом и подставкой.'],
['Рамка А4','350 ₽','Белая или чёрная.'],
['Кружка 330 мл','500 ₽','Белый фон, ваше фото, картинка или текст. Подарочная коробка и пакет включены. Редактура макета +150 ₽.'],
['Футболка','1 200 ₽','Белая, размер подбирается индивидуально. Печать фото, картинки или текста. Редактура макета +150 ₽.'],
['Журнал А4','от 3 000 ₽','20 страниц (10 двусторонних листов), скрепление пружиной. Ваши фотографии и тексты. Дополнительная страница — 100 ₽.'],
['Фотобук 10 × 15 см','775 ₽','15 односторонних листов. Скрепление пружиной. Фотографии и текст.']
]},
{id:'photos',label:'Фотопечать и сувениры',intro:'От отдельных отпечатков до маленьких памятных вещей.',poster:'photo',items:[
['Глянцевые фотографии','от 15 ₽','А4 — 100 ₽ · А5 — 50 ₽ · А6 — 25 ₽ · А7 — 15 ₽.'],
['Ламинирование фотографий','от 10 ₽','А4 — 70 ₽ · А5 — 50 ₽ · А6 — 30 ₽ · А7 — 10 ₽.'],
['Снимки в стиле Polaroid','20 ₽','За один отпечаток.'],
['Снимки в стиле Instax','15 ₽','За один отпечаток.'],
['Акриловый магнит 5 × 7 см','150 ₽','Магнит на холодильник с вашей фотографией.'],
['Виниловый магнит 5 × 9 см','170 ₽','Магнит на холодильник с вашей фотографией.'],
['3D-стикер 3 × 3 см','35 ₽','С вашей фотографией или изображением.'],
['Акриловый брелок 3 × 4 см','120 ₽','С вашей фотографией.'],
['3D-брелок 3 × 3 см','150 ₽','С вашей фотографией.'],
['Мини-фотоальбом','300 ₽','Брелок с 20 фотографиями.']
]},
{id:'print',label:'Печать документов',intro:'Документы, заявления, справки, бланки и учебные работы.',items:[
['Чёрно-белая печать','25 ₽ / страница','Для документов и других материалов.'],
['Печать с цветными элементами','35 ₽ / страница','Для материалов с цветными фрагментами. При большом объёме действует скидка.']
]}];
const productImages={"Полароидный дисплей": "poloroidniy_flip_display", "Фотокнижка": "photo_knizzka", "Рамка акриловая 10 × 15 см": "ramka_akril", "Рамка А4": "ramka_a4", "Кружка 330 мл": "kruska", "Футболка": "futbolka", "Фотобук 10 × 15 см": "sms_book", "Глянцевые фотографии": "photo_size", "Ламинирование фотографий": "photo_size", "Снимки в стиле Polaroid": "photo_poloroid", "Снимки в стиле Instax": "photo_insttax", "Акриловый магнит 5 × 7 см": "magnit_akriloviy", "Виниловый магнит 5 × 9 см": "magnit_viniloviy", "3D-стикер 3 × 3 см": "3d_sticers", "Акриловый брелок 3 × 4 см": "brelok_akril", "3D-брелок 3 × 3 см": "3d_brelok", "Мини-фотоальбом": "mini_photo_albom", "Журнал А4": "jurnal"};
const productImage=name=>productImages[name]?`<img src="./assets/products/${productImages[name]}-400.webp" srcset="./assets/products/${productImages[name]}-400.webp 400w, /assets/products/${productImages[name]}-800.webp 800w" sizes="(max-width:700px) 46vw, 360px" width="800" height="800" alt="${name}" loading="lazy" decoding="async">`:'<span>Фото товара</span>';
const serviceCard=([name,price,description])=>`<article class="service-card"><div class="service-image-slot" aria-label="${name}">${productImage(name)}</div><div class="service-card-body"><h3>${name}</h3><p>${description}</p><strong>${price}</strong><button data-contact="${name} · ${price}">Заказать</button></div></article>`;
function services(){document.title='Прочие услуги — Embrace the moment';app.innerHTML=categoryNav(true)+`<section class="services-page"><a class="back-link" href="#/">${icon('left')} На главную</a><div class="services-heading"><span class="eyebrow">Embrace the moment</span><h1>Прочие услуги</h1><p>Печатные подарки, фотографии и документы. Выберите то, что хочется сохранить или подарить.</p></div><nav class="service-jump" aria-label="Разделы услуг">${serviceGroups.map(g=>`<a href="#/services/${g.id}">${g.label}</a>`).join('')}</nav>${serviceGroups.map(g=>`<section class="service-group" id="${g.id}"><div class="service-group-head"><div><span class="eyebrow">${g.id==='print'?'Печать':'Сделано для вас'}</span><h2>${g.label}</h2><p>${g.intro}</p></div></div><div class="service-grid">${g.items.map(serviceCard).join('')}</div>${g.id==='photos'?'<p class="service-note">Размер фотографии меньше А7 можно подобрать индивидуально.</p>':''}</section>`).join('')}<div class="service-contact"><div><span class="eyebrow">Заказы и вопросы</span><h2>Расскажите, что хотите напечатать</h2><p>Подскажем по формату и срокам, уточним стоимость нестандартного заказа.</p></div><button class="button" data-contact="">Заказать или уточнить детали ${icon('arrow')}</button></div><p class="service-finish">Ваши материалы для печати остаются конфиденциальными. Условия индивидуального заказа уточняются перед изготовлением.</p></section>`;}

const card=t=>`<a class="card" href="#/template/${t.id}" style="--theme-accent:${t.accent}"><div class="card-art">${cover(t)}</div><div class="card-info"><h3>${t.name}</h3><div class="card-bottom"><span>от 3 000 ₽</span><span class="card-arrow">${icon('arrow')}</span></div></div></a>`;
const specs=()=>`<div class="specs" aria-label="Характеристики журнала"><div>${icon('paper')}<span>Формат<strong>А4 · 21 × 29,7 см</strong><small>На пружинке</small></span></div><div>${icon('palette')}<span>Печать<strong>Полноцветная</strong></span></div><div>${icon('clock')}<span>Изготовление<strong>3–4 рабочих дня</strong></span></div><div>${icon('photo')}<span>Наполнение<strong>Ваши фото и тексты</strong></span></div></div>`;
function home(){document.title='Embrace the moment — создай свой журнал';app.innerHTML=`${categoryNav()}<section class="hero"><div class="hero-copy"><span class="eyebrow">Личное становится вечным</span><h1>Создай свой<br><em>журнал.</em></h1><p>Твои истории. Твои моменты.<br>Журнал, в котором главное — ты.</p><a class="button" href="#/#templates">Выбрать макет ${icon('arrow')}</a><span class="hero-note">Для тех, кого хочется сохранить в словах.</span></div><div class="hero-art" aria-label="Журналы из коллекции Embrace">${cover(templates[2],'hero-back',true)}${cover(templates[0],'hero-front',true)}<span class="hero-signature">Сохраняй<br>главное</span></div></section><section class="collection" id="templates"><div class="section-heading"><span class="eyebrow">Коллекция личных историй</span><h2>С чего начнётся ваша?</h2><p>Четыре макета. Бесконечно много ваших историй.</p></div><div class="cards">${templates.map(card).join('')}</div>${specs()}</section><section class="how" id="how"><div class="how-heading"><span class="eyebrow">От идеи до журнала</span><h2>Легко создать.<br><em>Приятно сохранить.</em></h2></div><ol class="steps"><li><span>01</span><div><h3>Выберите свою историю</h3><p>Найдите макет и нужное количество страниц — от 20 до 36.</p></div></li><li><span>02</span><div><h3>Добавьте самое личное</h3><p>Загрузите фотографии, измените тексты и расположите всё по-своему.</p></div></li><li><span>03</span><div><h3>Сохраните готовый журнал</h3><p>Проверьте страницы в просмотре и сохраните макет для печати.</p></div></li></ol></section>`;}
function detail(t){document.title=`${t.name} — Embrace the moment`;app.innerHTML=`<article class="detail" style="--theme-accent:${t.accent}"><a class="back-link" href="#/#templates">${icon('left')} Все макеты</a><div class="product"><section class="product-gallery" aria-label="Примеры макета «${t.name}»"><div class="product-stage"><button class="gallery-nav gallery-prev" aria-label="Предыдущий пример">${icon('left')}</button><button class="gallery-image" aria-label="Увеличить пример макета"></button><button class="gallery-nav gallery-next" aria-label="Следующий пример">${icon('right')}</button><span class="gallery-counter" aria-live="polite"></span><button class="gallery-zoom" aria-label="Открыть изображение крупно">${icon('zoom')}</button></div><div class="gallery-tabs" role="group" aria-label="Выберите пример"><button data-slide="0" aria-pressed="true">${cover(t,'',false,'40px')}<span>Обложка</span></button><button data-slide="1" aria-pressed="false">${imageAsset('spread',t.id,'','','56px')}<span>${t.spreadLabel}</span></button></div><p class="gallery-caption" aria-live="polite"></p></section><section class="product-info"><span class="eyebrow">${t.tag}</span><h1>${t.name}</h1><p class="product-subtitle">${t.subtitle}</p><p class="product-description">${t.description}</p><div class="price-row"><span class="price">от 3 000 ₽</span><span class="price-note">Базовая цена за 20 страниц</span></div><fieldset><legend>Количество страниц</legend><div class="page-options">${[20,24,28,32,36].map(n=>`<label class="page-option"><input type="radio" name="pages" value="${n}" ${n===20?'checked':''}><span>${n}</span></label>`).join('')}</div></fieldset><p class="quantity-note" aria-live="polite">20 страниц, включая обложку</p><button class="button create">Создать журнал ${icon('arrow')}</button><p class="editor-note">Откроется редактор. Фото и тексты можно менять.</p></section></div>${specs()}<section class="inside"><div><span class="eyebrow">Внутри этого макета</span><h2>${t.spreadTitle}</h2><p>${t.hint}</p></div><ul>${t.chapters.map(s=>`<li>${icon('check')}<span>${s}</span></li>`).join('')}<li>${icon('check')}<span>Свободное редактирование всех страниц</span></li></ul></section></article>`;
let slide=0;const gallery=app.querySelector('.product-gallery'),slides=[{kind:'cover',src:`./assets/cover-${t.id}-spiral-960.webp`,alt:`Обложка журнала «${t.name}»`,caption:'Пример оформления обложки. Добавьте свои фотографии и слова.'},{kind:'spread',src:`./assets/spread-${t.id}-spiral-1536.webp`,alt:`Разворот «${t.spreadTitle}»`,caption:t.spreadDescription}];
function showSlide(n){slide=(n+slides.length)%slides.length;const s=slides[slide];gallery.querySelector('.gallery-image').innerHTML=imageAsset(s.kind,t.id,s.alt,slide?'spread-image':'cover-image',slide?'(max-width:700px) 95vw, 600px':'(max-width:700px) 72vw, 380px',true);gallery.querySelector('.product-stage').classList.toggle('show-spread',!!slide);gallery.querySelector('.gallery-counter').textContent=`${slide+1} / ${slides.length}`;gallery.querySelector('.gallery-caption').textContent=s.caption;gallery.querySelectorAll('[data-slide]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===slide)));}
gallery.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>showSlide(Number(b.dataset.slide)));gallery.querySelector('.gallery-prev').onclick=()=>showSlide(slide-1);gallery.querySelector('.gallery-next').onclick=()=>showSlide(slide+1);gallery.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();showSlide(slide+(e.key==='ArrowRight'?1:-1));}});
let touchStart=null,swiped=false;const stage=gallery.querySelector('.product-stage');stage.addEventListener('touchstart',e=>{touchStart={x:e.touches[0].clientX,y:e.touches[0].clientY};swiped=false;},{passive:true});stage.addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)){swiped=true;showSlide(slide+(dx<0?1:-1));}touchStart=null;},{passive:true});
function enlarge(){if(swiped){swiped=false;return;}const dialog=document.createElement('dialog');dialog.className='image-dialog';dialog.setAttribute('aria-label',slides[slide].alt);dialog.innerHTML=`<button class="image-close" aria-label="Закрыть изображение">${icon('close')}</button>${imageAsset(slides[slide].kind,t.id,slides[slide].alt,'enlarged-image','(max-width:700px) 98vw, 1000px',true)}<p>${slides[slide].caption}</p>`;document.body.append(dialog);dialog.querySelector('button').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();}
gallery.querySelector('.gallery-image').onclick=enlarge;gallery.querySelector('.gallery-zoom').onclick=enlarge;showSlide(0);
function updatePrice(){const pages=Number(app.querySelector('[name=pages]:checked').value),total=3000+(pages-20)*100;const price=app.querySelector('.price');price.setAttribute('aria-live','polite');price.textContent=total.toLocaleString('ru-RU')+' ₽';app.querySelector('.price-note').textContent=pages===20?'20 страниц · базовая стоимость':`${pages} страниц · 3 000 ₽ + ${(pages-20)*100} ₽ за дополнительные страницы`;app.querySelector('.quantity-note').textContent=`${pages} страниц, включая обложку. Дополнительная страница — 100 ₽, лист (2 страницы) — 200 ₽.`;}
app.querySelectorAll('[name="pages"]').forEach(r=>r.addEventListener('change',updatePrice));updatePrice();app.querySelector('.create').onclick=()=>{location.hash=`#/editor/${t.id}/${app.querySelector('[name=pages]:checked').value}`;};}
const menu=document.querySelector('#site-menu'),menuButton=document.querySelector('.menu-toggle');
function closeMenu(){menu.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Открыть меню');}
function route(){document.querySelector('.image-dialog')?.close();closeMenu();const editorMatch=location.hash.match(/^#\/editor\/(birthday|mama|love|blank)\/(20|24|28|32|36)$/);if(editorMatch){MagazineEditor.leave();MagazineEditor.mount(editorMatch[1],Number(editorMatch[2]));return;}MagazineEditor.leave();const path=location.hash||'#/';const serviceMatch=path.match(/^#\/services(?:\/(gifts|photos|print))?$/);if(serviceMatch){if(!app.querySelector('.services-page'))services();if(serviceMatch[1])requestAnimationFrame(()=>document.getElementById(serviceMatch[1])?.scrollIntoView());else window.scrollTo({top:0,behavior:'instant'});return;}const match=path.match(/^#\/template\/([^/]+)$/);if(match){const t=templates.find(t=>t.id===match[1]);if(t)detail(t);else{home();location.hash='#/';}window.scrollTo({top:0,behavior:'instant'});}else{if(!app.querySelector('.hero'))home();const anchor=path.split('#')[2];if(anchor)requestAnimationFrame(()=>document.getElementById(anchor)?.scrollIntoView());else window.scrollTo({top:0,behavior:'instant'});}}
menuButton.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню');});menu.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu();});document.addEventListener('click',e=>{if(!e.target.closest('.header'))closeMenu();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});window.addEventListener('hashchange',route);route();
